### ISSUE TITLE
Watch buzzer test

### ISSUE THREAD

**Issue by ArturoAmaya** [UHL-aid/UCSD-CSE-118-218-Team-D#3]
Make the watch buzz.

**Comment by ju-ra-96** [comment]
066bbdbf074034197b84acf8bc2b0c0b64b0d1ca basic Android watch app through which different vibrations can be tested

**Comment by ju-ra-96** [comment]
In the first iteration a basic watch app was created with three different vibrations and in a second iteration the UI was slightly adjusted and 7 more vibration patterns were added
