### ISSUE TITLE
Basic watch communication

### ISSUE THREAD

**Issue by ArturoAmaya** [UHL-aid/UCSD-CSE-118-218-Team-D#5]
Get basic communication between some kind of server on the pi and a client going. 

- [x] Server on the Pi
- [x] Client
- [x] Client on the watch
- [x] Communications protocol and format

**Comment by ArturoAmaya** [comment]
Commit #5854288e097e180f913545436dc2b0cb86a11259 adds the basics for a web server that uses WebSockets ass opposed to HTTP requests to send iformation between client and server. It currently runs on the Pi and we can access it from the world using NGrok HTTP tunnels.

**Comment by ArturoAmaya** [comment]
Protocol is (for now) send LEFT RIGHT or BOTH to the watch.

**Comment by ScottWebster6** [comment]
Commit https://github.com/UHL-aid/UCSD-CSE-118-218-Team-D/commit/051514d599f920d6d3784a1174f79ec6cd0232de finally figures out WebSocket connections using the OKHTTP library. Ready for testing with server.

**Comment by ArturoAmaya** [comment]
Tested with the server 5 minutes ago, all works
